# Generated by Django 5.2.8 on 2025-12-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('adopter_name', models.CharField(max_length=100)),
                ('adopted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
